import bigTreeTile from 'img/tiles/tree_16x32.png';
import smallTreeTile from 'img/tiles/tree_16x16.png';
import grassTile from 'img/tiles/grass_16x16.png';
import mudLightTile from 'img/tiles/mud_light_16x16.png';
import shrubLightTile from 'img/tiles/shrub_light_16x16.png';
import roadTile from 'img/tiles/road_mark_16x16.png';
import waterTile from 'img/tiles/water_16x16.png';
import waterLeftEdgeTile from 'img/tiles/water_edge_left_16x16.png';
import waterRightEdgeTile from 'img/tiles/water_edge_right_16x16.png';
import waterTopEdgeTile from 'img/tiles/water_edge_top_16x16.png';
import waterTopRightEdgeTile from 'img/tiles/water_edge_top_right_16x16.png';
import waterTopLeftEdgeTile from 'img/tiles/water_edge_top_left_16x16.png';
import snowBoulderTile from 'img/tiles/snow_boulder_16x16.png';
import snowGroundTile from 'img/tiles/snow_ground_16x16.png';
import snowGroundRocksTile from 'img/tiles/snow_ground_rocks_16x16.png';
import snowGrassTile from 'img/tiles/snow_grass_16x16.png';
import snowStumpLeftTile from 'img/tiles/snow_stump_left_16x32.png';
import snowStumpRightTile from 'img/tiles/snow_stump_right_16x32.png';
import { htmlImageFromSource as imgFromSource } from 'img/image-utils';

export const tree = imgFromSource(bigTreeTile);
export const smallTree = imgFromSource(smallTreeTile);
export const grass = imgFromSource(grassTile);
export const mudLight = imgFromSource(mudLightTile);
export const shrubLight = imgFromSource(shrubLightTile);
export const water = imgFromSource(waterTile);
export const waterLeftEdge = imgFromSource(waterLeftEdgeTile);
export const waterRightEdge = imgFromSource(waterRightEdgeTile);
export const waterTopEdge = imgFromSource(waterTopEdgeTile);
export const waterTopRightEdge = imgFromSource(waterTopRightEdgeTile);
export const waterTopLeftEdge = imgFromSource(waterTopLeftEdgeTile);
export const road = imgFromSource(roadTile);
export const snowBoulder = imgFromSource(snowBoulderTile);
export const snowGround = imgFromSource(snowGroundTile);
export const snowGroundRocks = imgFromSource(snowGroundRocksTile);
export const snowGrass = imgFromSource(snowGrassTile);
export const snowStumpLeft = imgFromSource(snowStumpLeftTile);
export const snowStumpRight = imgFromSource(snowStumpRightTile);
